name: interact
description: A collection of customizable interactive command-line components.
version: 2.2.1
repository: https://github.com/frencojobs/interact
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_console: ^4.1.0
  meta: ^1.15.0
  tint: ^2.0.1

dev_dependencies:
  lint: ^2.3.0
  test: ^1.25.5
